### PR TITLE
have code examples compile checked by GitHub Actions

### PR DESCRIPTION
**Pull request by mockersf**
This PR:
* moves code examples to a cargo project
* include the code files into the doc to still display them inline
* adds a cargo workspace that list the cargo projects containing code examples
* checks the cargo workspace in CI

With this, code samples are guaranteed to compile with the specified bevy version, and it's easier to track what is working with which bevy version, at the cost of some boilerplate. It does not stop writing inline code, but shows how to add code that will be checked.

I hope you find this helpful, but don't hesitate to ask questions or not merge if that's not your thing 👍

### CODE REVIEW

**Comment by mockersf** [comment]
related to #4 , let me try how that would work with code in example part of project

**Comment by mockersf** [comment]
it actually works even better with code in examples

**Comment by mockersf** [comment]
more info about what is possible for file include here: https://rust-lang.github.io/mdBook/format/mdbook.html#including-files
- complete file
- only a line
- between two lines
- a block defined by special comments
- hidden part of file may be revealed by user for context

**Comment by alice-i-cecile** [comment]
Oh fantastic, I was hoping this sort of functionality worked smoothly.

**Pull request merged**
